### ISSUE TITLE
دعم أمكانية الوصول Accessibility support

### ISSUE THREAD

**Issue by MesterPerfect** [muslimpack/HisnElmoslem_App#10]
السَلام عليكم ورحمة الله وبركاته 
بارك الله مجهوداتك أخي الكريم وجعلها الله في ميزان حسناتك 
هل يمكنك تطبيق إرشادات Flutter المتعلقة بإمكانية الوصول هنا 
وجزيت خيرا 

https://docs.flutter.dev/ui/accessibility-and-localization/accessibility

**Comment by HasanEltantawy** [comment]
وعليكم السلام ورحمة الله وبركاته 
آمين وبارك الله فيكم
إن شاء الله نعمل عليها في تحديثات مستقبليه

**Comment by MesterPerfect** [comment]
> وعليكم السلام ورحمة الله وبركاته آمين وبارك الله فيكم إن شاء الله نعمل عليها في تحديثات مستقبليه

شكرا لك وبالإنتظار
