### ISSUE TITLE
Add to F-droid repo

### ISSUE THREAD

**Issue by heberjeur** [muslimpack/HisnElmoslem_App#11]
Thank you for this application. Does this application contain third-party components or closed-source elements that are not available on F-Droid?

**Comment by 7Eltantawy** [comment]
No all-apps components are open and we try to Pulish it on fdroid

check request there:
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12122

**Comment by 7Eltantawy** [comment]
@heberjeur 
Check our app on f-droid
https://f-droid.org/packages/com.hassaneltantawy.hisnelmoslem/

**Comment by heberjeur** [comment]
Thanks 😊
