### ISSUE TITLE
add: Tafsir, Hadith, Sīrah, Qisas al-Anbiya, Masnavi

### ISSUE THREAD

**Issue by Pantyhose-X** [muslimpack/HisnElmoslem_App#18]
Islam. It's not just the Koran, it's !  People who should centralize it in the APP province should then go back and install apps for each of the classic texts
[Tafsir (exegesis)](https://en.wikipedia.org/wiki/Tafsir)
[Hadith](https://en.wikipedia.org/wiki/Hadith)
[Sirah](https://en.wikipedia.org/wiki/Prophetic_biography)
[Qisas al-Anbiya ("Stories of the Prophets")](https://en.wikipedia.org/wiki/Qisas_al-Anbiya)
[Masnavi](https://en.wikipedia.org/wiki/Masnavi)

### Maybe it should be a new app with the name "Muslim Classics," "Islam Classics."

**Comment by 7Eltantawy** [comment]
Our vision is to make apps separated and keep it simple.
So we have a separated app for each topic

check our website for more apps:
https://muslimpack.github.io/
