### ISSUE TITLE
استخدام الأرقام الهندية بديلا عن الأرقام الإنجليزية

### ISSUE THREAD

**Issue by heberjeur** [muslimpack/HisnElmoslem_App#19]
السلام عليكم،

أخي العزيز، نحن في بلدان المغرب العربي لا نفهم الأرقام الهندية، نحن نستعمل دوما الارقام الإنجليزية في كل شيئ، في المصحف الكريم، في كتبنا و مجلاتنا، في كل شيئ.

هل بإمكانك إضافة خيار في الإعدادات يمكننا من إختيار إما الأرقام الإنجليزية أو الهندية !

**Comment by 7Eltantawy** [comment]
وعليكم السلام ورحمة الله وبركاته
أبشر إن شاء الله

**Comment by heberjeur** [comment]
Hi, any updates about this please?

**Comment by 7Eltantawy** [comment]
The feature is now implemented and will ship it in the next release Insha Allah
@heberjeur
