### ISSUE TITLE
Put it on Fdroid.

### ISSUE THREAD

**Issue by Anonymous2716** [muslimpack/HisnElmoslem_App#3]
Nice Apps you built .QaDaa. And this one. Put this on fdroid like that one. And maybe add new language ` ENGLISH ` . README too.

**Comment by Anonymous2716** [comment]
InshaAllah.

**Comment by 4mohamedaliii** [comment]
> We'll work on that in future Insha'Allah.

عاش 
مستنيه ينزل على fdriod

**Comment by HasanEltantawy** [comment]
تم إرسال طلب لرفعه على fdriod
@4mohamedaliii

**Comment by 4mohamedaliii** [comment]
بقا متاح على fdriod ولا لسه؟

**Comment by HasanEltantawy** [comment]
@4mohamedaliii لسه
لو محتاج تحمله تقدر تحمله من هنا
https://github.com/muslimpack/HisnElmoslem_App/releases/tag/v2.0.0

**Comment by 7Eltantawy** [comment]
@4mohamedaliii  @Anonymous2716 
Check our app on f-droid
https://f-droid.org/packages/com.hassaneltantawy.hisnelmoslem/

**Comment by Anonymous2716** [comment]
@7Eltantawy  jzkallah
