### ISSUE TITLE
طلب

### ISSUE THREAD

**Issue by ghazouani1212** [muslimpack/HisnElmoslem_App#9]
اولا جزاك الله خير
 لي طلب ارجوا منكم اضافة نسخة في متجر  F-droid 
هذه العلة الوحيدة التي صادفتها 🙂

**Comment by HasanEltantawy** [comment]
آمين وجزاكم

نحن نعمل على رفعه هناك

يمكنك تحميل التطبيق من الـ Release داخل الـ Repo
